version: '3.2'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - api
      - web
    restart: always
    environment:
      DOMAINS: >
        nagata.pro -> http://web, 
        www.nagata.pro -> http://web, 
        api.nagata.pro -> http://api
      STAGE: staging
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
      RENEW_MARGIN_DAYS: 7
    volumes:
      - type: bind
        source: ./ssl-certs
        target: /var/lib/https-portal

  api:
    restart: always
    build:
      context: ./api
    command: python main.py

  hugo:
    restart: always
    build:
      context: ./web
    environment:
      TZ: Asia/Tokyo
    volumes:
      - type: bind
        source: ./web/hugo
        target: /hugo

  web:
    image: joseluisq/static-web-server:2
    environment:
      - SERVER_ROOT=/public
    volumes:
      - type: bind
        source: ./web/hugo/public
        target: /public
    depends_on:
      - hugo

volumes:
  https-portal-data: